// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Bundle struct {
	ItemID   int `json:"itemID"`
	Quantity int `json:"quantity"`
}

type Mutation struct {
}

type Query struct {
}
